# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: dbrest

before:
  hooks:
    - go mod edit -dropreplace='github.com/flarco/g' go.mod
    - go mod edit -dropreplace='github.com/slingdata-io/sling-cli' go.mod
    - go mod edit -droprequire='github.com/slingdata-io/sling' go.mod
    - go mod tidy

builds:
  - main: .
    
    env:
      - CGO_ENABLED=1

    goarch:
      - amd64
      - arm64
    goos:
      # - linux
      # - windows
      - darwin
    ldflags:
      - "-X 'github.com/dbrest-io/dbrest/state.Version={{ .Version }}' -X 'github.com/dbrest-io/dbrest/state.RudderstackURL={{ .Env.RUDDERSTACK_URL }}'"

universal_binaries:
  - id: dbrest
    replace: false
  
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Runtime.Goos }}_{{ .Runtime.Goarch }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}"

release:
  mode: replace
  header: |
    ## dbREST {{ .Tag }} ({{ .Date }})

brews:
  - name: dbrest
    repository:
      owner: dbrest-io
      name: homebrew-dbrest
      branch: main

    homepage: https:/github.com/dbrest-io/dbrest

    description: "dbREST is an API backend that you can put in front of your database. Ever wanted to spin up an API service in front of your Snowflake, MySQL or even SQLite database? Well, dbREST allows that!"